import { Receipt } from "lucide-react"
import type { ResourceConfig } from "@/admin/types"

export const invoices: ResourceConfig = {
  name: "invoices",
  label: "Hisob-faktura",
  labelPlural: "Hisob-fakturalar",
  icon: Receipt,
  group: "Moliya",
  description: "To'lov hujjatlari, summalar va muddatlar",
  recordLabel: (r) => `INV-${r.number ?? r.id}`,
  defaultSort: { field: "issuedAt", order: "desc" },
  searchPlaceholder: "Hisob-faktura raqami bo'yicha qidirish...",
  fields: [
    {
      name: "number",
      label: "Raqam",
      type: "text",
      primary: true,
      prefix: "INV-",
      searchable: true,
      sortable: true,
      required: true,
    },
    {
      name: "customer",
      label: "Mijoz",
      type: "relation",
      relation: { resource: "users" },
      sortable: true,
      required: true,
    },
    {
      name: "amount",
      label: "Summa",
      type: "currency",
      currency: "USD",
      sortable: true,
      align: "end",
      required: true,
      min: 0,
      step: 0.01,
      defaultValue: 0,
    },
    {
      name: "status",
      label: "Holat",
      type: "badge",
      sortable: true,
      filterable: true,
      defaultValue: "draft",
      options: [
        { value: "draft", label: "Qoralama", tone: "neutral" },
        { value: "sent", label: "Yuborilgan", tone: "info" },
        { value: "paid", label: "To'langan", tone: "success" },
        { value: "overdue", label: "Muddati o'tgan", tone: "danger" },
        { value: "void", label: "Bekor qilingan", tone: "warning" },
      ],
    },
    {
      name: "method",
      label: "To'lov usuli",
      type: "select",
      filterable: true,
      defaultValue: "transfer",
      options: [
        { value: "card", label: "Karta" },
        { value: "transfer", label: "O'tkazma" },
        { value: "cash", label: "Naqd" },
      ],
    },
    {
      name: "issuedAt",
      label: "Berilgan",
      type: "date",
      sortable: true,
      align: "end",
    },
    {
      name: "dueAt",
      label: "To'lov muddati",
      type: "date",
      sortable: true,
      align: "end",
    },
  ],
}
