import { ShoppingCart } from "lucide-react"
import type { ResourceConfig } from "@/admin/types"

export const orders: ResourceConfig = {
  name: "orders",
  label: "Buyurtma",
  labelPlural: "Buyurtmalar",
  icon: ShoppingCart,
  group: "Savdo",
  description: "Tranzaksiyalar va to'lov holatlari",
  recordLabel: (r) => `#${r.number ?? r.id}`,
  defaultSort: { field: "date", order: "desc" },
  searchPlaceholder: "Buyurtma raqami bo'yicha qidirish...",
  fields: [
    {
      name: "number",
      label: "Buyurtma",
      type: "text",
      primary: true,
      prefix: "#",
      searchable: true,
      sortable: true,
      required: true,
    },
    {
      name: "customer",
      label: "Mijoz",
      type: "relation",
      relation: { resource: "users" },
      sortable: true,
      required: true,
    },
    {
      name: "amount",
      label: "Summa",
      type: "currency",
      currency: "USD",
      sortable: true,
      align: "end",
      required: true,
      min: 0,
      step: 0.01,
      defaultValue: 0,
    },
    {
      name: "status",
      label: "Holat",
      type: "badge",
      sortable: true,
      filterable: true,
      defaultValue: "pending",
      options: [
        { value: "paid", label: "To'langan", tone: "success" },
        { value: "pending", label: "Kutilmoqda", tone: "warning" },
        { value: "refunded", label: "Qaytarilgan", tone: "info" },
        { value: "failed", label: "Muvaffaqiyatsiz", tone: "danger" },
      ],
    },
    {
      name: "items",
      label: "Mahsulotlar",
      type: "number",
      align: "end",
      min: 1,
      defaultValue: 1,
    },
    {
      name: "method",
      label: "To'lov usuli",
      type: "select",
      filterable: true,
      defaultValue: "card",
      options: [
        { value: "card", label: "Karta" },
        { value: "cash", label: "Naqd" },
        { value: "transfer", label: "O'tkazma" },
      ],
    },
    {
      name: "date",
      label: "Sana",
      type: "date",
      sortable: true,
      align: "end",
    },
  ],
}
