import { Package } from "lucide-react"
import type { ResourceConfig } from "@/admin/types"

export const products: ResourceConfig = {
  name: "products",
  label: "Mahsulot",
  labelPlural: "Mahsulotlar",
  icon: Package,
  group: "Katalog",
  description: "Inventar, narxlar va kategoriyalar",
  recordLabel: (r) => String(r.name ?? r.id),
  defaultSort: { field: "createdAt", order: "desc" },
  searchPlaceholder: "Nomi yoki SKU bo'yicha qidirish...",
  fields: [
    {
      name: "name",
      label: "Nomi",
      type: "text",
      primary: true,
      searchable: true,
      sortable: true,
      required: true,
      placeholder: "Mahsulot nomi",
    },
    {
      name: "sku",
      label: "SKU",
      type: "text",
      searchable: true,
      placeholder: "SKU-00000",
    },
    {
      name: "category",
      label: "Kategoriya",
      type: "badge",
      sortable: true,
      filterable: true,
      defaultValue: "Elektronika",
      options: [
        { value: "Elektronika", label: "Elektronika", tone: "info" },
        { value: "Aksessuar", label: "Aksessuar", tone: "primary" },
        { value: "Mebel", label: "Mebel", tone: "warning" },
        { value: "Audio", label: "Audio", tone: "success" },
        { value: "Ofis", label: "Ofis", tone: "neutral" },
      ],
    },
    {
      name: "price",
      label: "Narx",
      type: "currency",
      currency: "USD",
      sortable: true,
      align: "end",
      required: true,
      min: 0,
      step: 0.01,
      defaultValue: 0,
    },
    {
      name: "stock",
      label: "Zaxira",
      type: "number",
      sortable: true,
      align: "end",
      min: 0,
      defaultValue: 0,
    },
    {
      name: "active",
      label: "Faol",
      type: "boolean",
      filterable: true,
      defaultValue: true,
    },
    {
      name: "color",
      label: "Rang",
      type: "color",
      hideInTable: true,
      defaultValue: "#7c5cff",
    },
    {
      name: "createdAt",
      label: "Qo'shilgan",
      type: "date",
      sortable: true,
      align: "end",
    },
  ],
}
