import { Briefcase } from "lucide-react"
import type { ResourceConfig } from "@/admin/types"

export const projects: ResourceConfig = {
  name: "projects",
  label: "Loyiha",
  labelPlural: "Loyihalar",
  icon: Briefcase,
  group: "Ish",
  description: "Jamoa loyihalari, byudjet va bajarilish holati",
  recordLabel: (r) => String(r.name ?? r.id),
  defaultSort: { field: "dueDate", order: "asc" },
  searchPlaceholder: "Loyiha nomi bo'yicha qidirish...",
  fields: [
    {
      name: "name",
      label: "Loyiha",
      type: "text",
      primary: true,
      searchable: true,
      sortable: true,
      required: true,
      placeholder: "Loyiha nomi",
    },
    {
      name: "owner",
      label: "Mas'ul",
      type: "relation",
      relation: { resource: "users" },
      sortable: true,
      required: true,
    },
    {
      name: "status",
      label: "Holat",
      type: "badge",
      sortable: true,
      filterable: true,
      defaultValue: "planning",
      options: [
        { value: "planning", label: "Rejalashtirish", tone: "info" },
        { value: "active", label: "Jarayonda", tone: "primary" },
        { value: "on_hold", label: "To'xtatilgan", tone: "warning" },
        { value: "completed", label: "Yakunlangan", tone: "success" },
      ],
    },
    {
      name: "priority",
      label: "Muhimlik",
      type: "badge",
      filterable: true,
      defaultValue: "medium",
      options: [
        { value: "low", label: "Past", tone: "neutral" },
        { value: "medium", label: "O'rta", tone: "info" },
        { value: "high", label: "Yuqori", tone: "danger" },
      ],
    },
    {
      name: "budget",
      label: "Byudjet",
      type: "currency",
      currency: "USD",
      sortable: true,
      align: "end",
      min: 0,
      defaultValue: 0,
    },
    {
      name: "progress",
      label: "Bajarildi",
      type: "number",
      suffix: "%",
      align: "end",
      sortable: true,
      min: 0,
      max: 100,
      defaultValue: 0,
    },
    {
      name: "startDate",
      label: "Boshlanish",
      type: "date",
      hideInTable: true,
    },
    {
      name: "dueDate",
      label: "Muddat",
      type: "date",
      sortable: true,
      align: "end",
    },
  ],
}
