import { Users } from "lucide-react"
import type { ResourceConfig } from "@/admin/types"

export const users: ResourceConfig = {
  name: "users",
  label: "Foydalanuvchi",
  labelPlural: "Foydalanuvchilar",
  icon: Users,
  group: "Asosiy",
  description: "Hisoblar, rollar va obuna rejalari",
  recordLabel: (r) => String(r.name ?? r.email ?? r.id),
  defaultSort: { field: "createdAt", order: "desc" },
  searchPlaceholder: "Ism yoki email bo'yicha qidirish...",
  fields: [
    {
      name: "name",
      label: "Foydalanuvchi",
      type: "avatar",
      primary: true,
      searchable: true,
      sortable: true,
      required: true,
      placeholder: "To'liq ism",
    },
    {
      name: "email",
      label: "Email",
      type: "email",
      searchable: true,
      sortable: true,
      required: true,
      placeholder: "user@example.com",
    },
    {
      name: "role",
      label: "Rol",
      type: "badge",
      sortable: true,
      filterable: true,
      defaultValue: "member",
      options: [
        { value: "admin", label: "Admin", tone: "primary" },
        { value: "manager", label: "Menejer", tone: "info" },
        { value: "member", label: "A'zo", tone: "neutral" },
        { value: "viewer", label: "Kuzatuvchi", tone: "neutral" },
      ],
    },
    {
      name: "status",
      label: "Holat",
      type: "badge",
      sortable: true,
      filterable: true,
      defaultValue: "invited",
      options: [
        { value: "active", label: "Faol", tone: "success" },
        { value: "invited", label: "Taklif qilingan", tone: "warning" },
        { value: "suspended", label: "Bloklangan", tone: "danger" },
      ],
    },
    {
      name: "plan",
      label: "Reja",
      type: "badge",
      filterable: true,
      defaultValue: "free",
      options: [
        { value: "free", label: "Free", tone: "neutral" },
        { value: "pro", label: "Pro", tone: "info" },
        { value: "enterprise", label: "Enterprise", tone: "primary" },
      ],
    },
    {
      name: "balance",
      label: "Balans",
      type: "currency",
      currency: "USD",
      sortable: true,
      align: "end",
      defaultValue: 0,
      min: 0,
    },
    {
      name: "country",
      label: "Davlat",
      type: "text",
      hideInTable: true,
      placeholder: "O'zbekiston",
    },
    {
      name: "createdAt",
      label: "Qo'shilgan",
      type: "date",
      sortable: true,
      align: "end",
    },
  ],
}
